version: "3"

services:
  app:
    image: mattermost/focalboard
    container_name: focalboard
    depends_on:
      - focalboard-db
    ports:
      - 8003:8000
    volumes:
      - "./config.json:/opt/focalboard/config.json"
    restart: always


  focalboard-db:
    image: postgres:latest
    container_name: focalboard-postgres
    restart: always
    volumes:
      - "./data:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: boards
      POSTGRES_USER: boardsuser
      POSTGRES_PASSWORD: boardsuser-password

