version: "3.3"

services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8889:8888
    volumes:
      - ./workspace:/home/jovyan/work
    environment:
      JUPYTER_ENABLE_LAB: "yes"
      JUPYTER_TOKEN: "docker"
