[http.middlewares.simpleAuth.basicAuth]
  users = [
    "admin:$apr1$izVXzpYy$sXrGiTEHo5yx1UtzMwwAk/"
  ]

[http.routers.api]
  rule = "Host(`xxx.xxx`)"
  entrypoints = ["websecure"]
  middlewares = ["simpleAuth"]
  service = "api@internal"
  [http.routers.api.tls]
    certResolver = "lets-encrypt"

[http.routers.api-omvpb]
  rule = "Host(`yyy.yyy`)"
  entrypoints = ["websecure"]
  service = "api-omvpb"
  [http.routers.api-omvpb.tls]
    certResolver = "lets-encrypt"

[http.services]
  [http.services.api-omvpb.loadBalancer]
    passHostHeader = true
    [[http.services.api-omvpb.loadBalancer.servers]]
      url = "http://@ip:9080/"
