[http.middlewares.simpleAuth.basicAuth]
  users = [
    "admin:$apr1$izVXzpYy$sXrGiTEHo5yx1UtzMwwAk/"
  ]

[http.routers.api]
  rule = "Host(`xxx.xxx`)"
  entrypoints = ["websecure"]
  middlewares = ["simpleAuth"]
  service = "api@internal"
  [http.routers.api.tls]
    certResolver = "lets-encrypt"

[http.routers.api-omvpb]
  rule = "Host(`yyy.yyy`)"
  entrypoints = ["websecure"]
  middlewares = ["testHeaderApi"]
  service = "api-omvpb"
  [http.routers.api-omvpb.tls]
    certResolver = "lets-encrypt"

[http.services]
  [http.services.api-omvpb.loadBalancer]
    passHostHeader = true
    [[http.services.api-omvpb.loadBalancer.servers]]
      url = "http://@ip:9080/"

[http.middlewares.testHeaderApi.headers]
    accessControlAllowMethods= ["GET", "OPTIONS", "PUT", "POST", "DELETE"]
    accessControlAllowOriginList = ["*"]
    accessControlMaxAge = 100
    addVaryHeader = true
    accessControlAllowHeaders=["Origin", "Accept", "Content-Type", "X-Requested-With", "X-CSRF-Token", "api-key"]
