version: "3"

services:
  flarum:
    image: mondedie/flarum:stable
    container_name: flarum
    volumes:
      - ./mnt/docker/flarum/assets:/flarum/app/public/assets
      - ./mnt/docker/flarum/extensions:/flarum/app/extensions
      - ./mnt/docker/flarum/storage/logs:/flarum/app/storage/logs
      - ./mnt/docker/flarum/nginx:/etc/nginx/flarum
    ports:
      - 8088:8888
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.5
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=aaa
      - MYSQL_DATABASE=flarum
      - MYSQL_USER=flarum
      - MYSQL_PASSWORD=aa
    volumes:
      - ./mnt/docker/mysql/db:/var/lib/mysql
