# Siberian CMS SAE docker stack
version: '3.7'

services:
  mysql:
    image: mariadb:10.5
    container_name: mysql_siberian
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: siberian
      MYSQL_USER: siberian
      MYSQL_PASSWORD: siberian
    volumes:
      - db:/var/lib/mysql:rw
#    ports:
#        - 3306:3306/tcp
  web:
    image: rylorin/siberiancms:latest
    depends_on:
      - mysql
    volumes:
      - htdocs:/var/www/html:rw
    ports:
        - 80:80/tcp
volumes:
  db:
  htdocs:
