version: "3.8"
services:
  nginx-web:
    image : nginx
    restart: always
    volumes:
      - ./data:/var/www/html
      - ./conf:/etc/nginx/conf.d/
    networks:
      - traefik-proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.nginx-web.rule=Host(`${URL_PWA}`) 
      - traefik.http.routers.nginx-web.entrypoints=websecure
      - traefik.http.routers.nginx-web.tls=true
      - traefik.http.routers.nginx-web.tls.certresolver=lets-encrypt
      - traefik.http.services.nginx-web.loadbalancer.server.port=80

networks:
  traefik-proxy:
    external:
      name: ${NETWORK_TRAEFIK}
      
