version: "3.9"
    
services:
  db:
    image: mysql:5.7
    volumes:
      - mysqlwordpress:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - datawordpress:/var/www/html
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress      

    
volumes:
 mysqlwordpress:
    driver: local
    driver_opts:
      type: none
      device: ${VOLUME_MYSQL_WORDPRESS}
      o: bind

 datawordpress:
    driver: local
    driver_opts:
      type: none
      device: ${VOLUME_DATA_WORDPRESS}
      o: bind