version: "3"
services:
  redis:
    image: redis
    ports:
      - "6479:6379"
  postgres:
    image: postgres
    ports:
      - "5532:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: outline
  s3:
    image: lphoward/fake-s3
    ports:
      - "4569:4569"
    volumes:
      - ./fakes3:/fakes3_root
  outline:
    image: outlinewiki/outline
    command:
      - yarn db:migrate
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
      - s3
