version: "3.3"
services:
  signaturepdf:
    build:
      context: ./
    hostname: signaturepdf
    restart: always
    logging:
      options:
        max-size: '12m'
        max-file: '5'
      driver: json-file
    environment:
      - SERVERNAME=${URL_SIGNATURE}
    labels:
      - traefik.enable=true
      - traefik.http.routers.signaturepdf.rule=Host(`${URL_SIGNATURE}`)
      - traefik.http.routers.signaturepdf.entrypoints=websecure
      - traefik.http.routers.signaturepdf.tls=true
      - traefik.http.routers.signaturepdf.tls.certresolver=lets-encrypt
      - traefik.http.services.signaturepdf.loadbalancer.server.port=80
    volumes:
      - signature-data:/data
    networks:
      - hosting_web

networks:
  hosting_web:
    external:
      name: ${NETWORK_TRAEFIK}

volumes:
  signature-data:
     driver: local
     driver_opts:
      type: none
      device: ${SIGNATURE_DATA}
      o: bind

